.github/workflows/okta-mobile.yaml, README.md, Sources/AuthFoundation/JWT/Internal/DefaultAccessTokenValidator.swift, Sources/AuthFoundation/Requests/Token+Requests.swift, Sources/AuthFoundation/Token Management/Internal/KeychainTokenStorage.swift, Sources/AuthFoundation/Token Management/Internal/UserDefaultsTokenStorage.swift, Sources/AuthFoundation/Token Management/Token.swift, Sources/AuthFoundation/Token Management/TokenStorage.swift, Sources/AuthFoundation/User Management/Credential.swift, Sources/AuthFoundation/User Management/Internal/CredentialCoordinator.swift, Tests/AuthFoundationTests/CredentialCoordinatorTests.swift, Tests/AuthFoundationTests/CredentialTests.swift, Tests/AuthFoundationTests/DefaultCredentialDataSourceTests.swift, Tests/AuthFoundationTests/KeychainTokenStorageTests.swift, Tests/AuthFoundationTests/OAuth2ClientTests.swift, Tests/AuthFoundationTests/TokenTests.swift, Tests/AuthFoundationTests/UserDefaultsTokenStorageTests.swift, Tests/TestCommon/MockCredentialCoordinator.swift, Tests/TestCommon/MockToken.swift, Tests/TestCommon/MockTokenStorage.swift
This permits tokens to be uniquely identified by UUIDs, and to associate custom developer-assigned metadata to retrieve tokens based on their arguments.
=> Add unique ID for tokens, and associated metadata

.github/workflows/ui-tests.yaml
Intermittent CI failures were occurring due to Swift Package Manager unable to resolve dependencies. It seems to be related to this issue: https://forums.swift.org/t/xcode-and-swift-package-manager/44704/6
=> Move DerivedData folder out of the cloned Git repo to stabilize SPM

Samples/DeviceAuthSignIn/DeviceAuthSignInUITests (iOS)/Pages/BrowserSignInScreen.swift, Samples/Shared/Common/Testing/XCTest+Extensions.swift
1 second isn't long enough to wait for device authorization grant token exchange within CI.
=> Increase device activation wait time in UI test

Sources/AuthFoundation/AuthFoundation.docc/AuthFoundation.md, Sources/AuthFoundation/OAuth2/Authentication.swift, Sources/OktaOAuth2/Authentication/AuthorizationCodeFlow.swift, Sources/OktaOAuth2/Authentication/DeviceAuthorizationFlow.swift, Sources/OktaOAuth2/Authentication/ResourceOwnerFlow.swift, Sources/OktaOAuth2/Authentication/TokenExchangeFlow.swift, Sources/OktaOAuth2/Logout/Logout.swift, Sources/WebAuthenticationUI/WebAuthentication.swift
The `AuthenticationFlow` protocol required both a `cancel` and `reset` function, but there wasn't any clear reason for both of those to exist. This change removes the `cancel` requirement, in favour of a more general catch-all `reset`.
=> Remove redundant `cancel` AuthenticationFlow function

Samples/DeviceAuthSignIn/DeviceAuthSignIn (tvOS)/DeviceAuthSignIn/ViewController.swift, Samples/DeviceAuthSignIn/DeviceAuthSignIn.xcodeproj/xcshareddata/xcschemes/DeviceAuthSignIn (tvOS).xcscheme, Sources/OktaOAuth2/Authentication/DeviceAuthorizationFlow.swift, Tests/OktaOAuth2Tests/DeviceAuthorizationFlowErrorTests.swift, Tests/OktaOAuth2Tests/MockResponses/token-authorization_pending.json, Tests/OktaOAuth2Tests/MockResponses/token-slow_down.json, Tests/OktaOAuth2Tests/Utilities/DeviceAuthorizationFlowDelegateRecorder.swift, Tests/WebAuthenticationUITests/AuthenticationServicesProviderTests.swift
Corresponds to https://github.com/okta/okta-mobile-kotlin/pull/186
=> Support the `slow_down` token error response in DeviceAuthorizationFlow

Samples/DeviceAuthSignIn/DeviceAuthSignIn (tvOS)/DeviceAuthSignIn/ViewController.swift, Samples/Shared/Common/ViewControllers/TokenDetailViewController.swift, Sources/AuthFoundation/JWT/JWK.swift, Sources/AuthFoundation/Token Management/Token.swift, Sources/OktaOAuth2/Authentication/DeviceAuthorizationFlow.swift, Sources/WebAuthenticationUI/WebAuthenticationUI.docc/CustomizingAuthorizationURL.md, Tests/AuthFoundationTests/DefaultJWKValidatorTests.swift, Tests/AuthFoundationTests/JWKTests.swift, Tests/AuthFoundationTests/TokenTests.swift, Tests/OktaOAuth2Tests/DeviceAuthorizationFlowSuccessTests.swift
This matches up to https://github.com/okta/okta-mobile-kotlin/pull/183 and https://github.com/okta/okta-mobile-kotlin/pull/182
=> Update device authorization and JWKS to closer match the spec

Sources/AuthFoundation/OAuth2/OAuth2Client.swift, Sources/AuthFoundation/Token Management/Token.swift, Tests/OktaOAuth2Tests/OAuth2ClientTests.swift
* To support the use of vanity domains, it’s important to use the issuer URL from the opened-configuration when performing ID Token validation.
=> Use openIdConfiguration issuer when verifying ID token  issuer claim

Samples/UserPasswordSignIn/UserPasswordSignIn Tests/SignInTests.swift, Sources/AuthFoundation/Requests/Token+Requests.swift, Tests/AuthFoundationTests/OAuth2ClientTests.swift
- Include the client_id as a query parameter when calling the /introspect endpoint. 
- do not pass the Authorization header in the request
- Link to swagger doc:  https://developer.okta.com/docs/reference/api/oidc/#introspect
=> Supply client_id to Introspect request call

Sources/AuthFoundation/Network/APIClientError.swift, Sources/AuthFoundation/Network/OktaAPIError.swift, Sources/AuthFoundation/OAuth2/OAuth2Client.swift, Sources/AuthFoundation/OAuth2/OAuth2Error.swift, Sources/AuthFoundation/Responses/OAuth2ServerError.swift, Tests/AuthFoundationTests/CredentialRefreshTests.swift, Tests/AuthFoundationTests/OAuth2ClientTests.swift, Tests/TestCommon/MockToken.swift, Tests/WebAuthenticationUITests/WebAuthTests.swift
Additionally, ensure some error types are equatable, to make testing simpler.
=> Ensure refresh token is present before trying to refresh.

Sources/AuthFoundation/OAuth2/OAuth2Client.swift, Tests/TestCommon/MockToken.swift
In the previous PR #102 the refresh handling added verification checks to ensure the refresh token was present before triggering a refresh, so the appropriate error message can be returned. However, this was pulling the refresh token from a property of `clientSettings` which no longer was present in new builds of the SDK.
This update changes this behaviour to use the refresh token directly from the Token object instead.
=> Stop using the refresh token from the clientSettings, since it's no longer stored there

OktaAuthFoundation.podspec, OktaOAuth2.podspec, OktaWebAuthenticationUI.podspec, README.md, Samples/Shared/Common/ViewControllers/ProfileTableViewController.swift, Sources/AuthFoundation/OAuth2/OAuth2Client.swift, Sources/AuthFoundation/User Management/Credential.swift, Sources/AuthFoundation/User Management/CredentialCoordinator.swift, Sources/AuthFoundation/User Management/Internal/CredentialCoordinatorImpl.swift, Sources/AuthFoundation/Version.swift, Sources/OktaOAuth2/Version.swift, Sources/WebAuthenticationUI/Version.swift, Tests/AuthFoundationTests/CredentialCoordinatorTests.swift, Tests/TestCommon/MockCredentialCoordinator.swift
This fixes https://github.com/okta/okta-idx-swift/issues/120
Ultimately the root cause was due to the CredentialCoordinatorImpl relying on NSNotifications to detect the creation of a new OAuth2Client so it could be added as a delegate. However, if the client is created _before_ the CredentialCoordinatorImpl, then it won't be able to receive delegate calls to [oauth(client:didRefresh:replacedWith:)](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/oauth2clientdelegate/oauth(client:didrefresh:replacedwith:)-2rj5a), which is used to trigger a token storage.
This fix works around the issue by having the OAuth2Client explicitly add itself to the CredentialCoordinator, causing it to be initialized on-demand.
=> Fix a race condition that sometimes prevents tokens from being stored after a refresh

OktaAuthFoundation.podspec, OktaOAuth2.podspec, OktaWebAuthenticationUI.podspec, README.md, Sources/AuthFoundation/Network/APIClient.swift, Sources/AuthFoundation/Network/APIRequest.swift, Sources/AuthFoundation/Network/APIResponse.swift, Sources/AuthFoundation/Responses/OAuth2ServerError.swift, Sources/AuthFoundation/Version.swift, Sources/OktaOAuth2/Version.swift, Sources/WebAuthenticationUI/Version.swift, Tests/AuthFoundationTests/APIClientTests.swift, Tests/AuthFoundationTests/ErrorTests.swift, Tests/AuthFoundationTests/OAuth2ClientTests.swift
Some API responses may use status codes to indicate error states that are still actionable, accompanied by a response body. This update enables developers to customize response handling to ensure those bodies are still consumable.
=> Support customizing HTTP status code handling

Samples/Shared/Common/ViewControllers/ProfileTableViewController.swift, Samples/Shared/Common/ViewControllers/TokenDetailViewController.swift, Sources/AuthFoundation/User Management/Credential.swift, Sources/AuthFoundation/User Management/Internal/Credential+Internal.swift, Tests/AuthFoundationTests/CredentialInternalTests.swift, Tests/TestCommon/MockCredentialCoordinator.swift, Tests/TestCommon/MockToken.swift
In response to #115 I added features to demonstrate token revocation, to simplify debugging.
=> Add option to test revoke within the sample app, and improve shouldRemove handling

Sources/AuthFoundation/OAuth2/Configuration.swift, Sources/AuthFoundation/User Management/Credential+Extensions.swift, Sources/AuthFoundation/User Management/Internal/CredentialCoordinatorImpl.swift
There was an added attribute to the OAuth2 client configuration, but it didn't account for migrations when the value was not present from previous releases. This fixes #138
=> Fix migration of tokens from previous releases

Sources/AuthFoundation/OAuth2/OAuth2Client.swift, Sources/AuthFoundation/Requests/OpenIdConfigurationRequest.swift
**Enhancements in OAuth2Client & OpenIdConfigurationRequest**
- Properly utilize the passed discovery URL in `OAuth2Client.swift`. Previously, it was only being set but not used.
- Eliminated redundant logic: The logic to append `.well-known` to the URL was duplicated in both `OpenIdConfigurationRequest` and the `OAuth2Client.swift` initializer. This has now been streamlined, removing the redundancy from `OpenIdConfigurationRequest`.
---
=> Using discovery url

Sources/AuthFoundation/Network/APIRequest.swift, Sources/AuthFoundation/OAuth2/OAuth2Client.swift, Sources/AuthFoundation/Token Management/Token.swift, Sources/AuthFoundation/User Management/Credential+Extensions.swift, Sources/OktaDirectAuth/DirectAuthFlow.swift, Sources/OktaOAuth2/Authentication/AuthorizationCodeFlow.swift, Sources/OktaOAuth2/Authentication/DeviceAuthorizationFlow.swift, Sources/OktaOAuth2/Authentication/ResourceOwnerFlow.swift, Sources/OktaOAuth2/Authentication/SessionTokenFlow.swift, Sources/OktaOAuth2/Authentication/TokenExchangeFlow.swift, Sources/OktaOAuth2/Logout/SessionLogoutFlow.swift, Sources/WebAuthenticationUI/Extensions/WebAuthentication+Deprecated.swift, Sources/WebAuthenticationUI/WebAuthentication.swift, Tests/AuthFoundationTests/CredentialRefreshTests.swift, Tests/AuthFoundationTests/OAuth2ClientTests.swift, Tests/AuthFoundationTests/TokenTests.swift, Tests/OktaDirectAuthTests/DirectAuth1FATests.swift, Tests/OktaDirectAuthTests/DirectAuth2FATests.swift, Tests/OktaOAuth2Tests/AuthorizationCodeFlowSuccessTests.swift, Tests/OktaOAuth2Tests/DeviceAuthorizationFlowSuccessTests.swift, Tests/OktaOAuth2Tests/ResourceOwnerFlowTests.swift, Tests/OktaOAuth2Tests/SessionLogoutFlowSuccessTests.swift, Tests/OktaOAuth2Tests/SessionTokenFlowTests.swift, Tests/OktaOAuth2Tests/TokenExchangeFlowTests.swift, Tests/TestCommon/URLSessionMock.swift
All async/await APIs are currently only available for iOS 15 but the minimum requirement for async/await is iOS 13. This PR changes the minimum iOS version from 15 to 13 where possible.
=> Obvious Fix: Change minimum iOS version from 15 to 13 where possible

OktaAuthFoundation.podspec, OktaDirectAuth.podspec, OktaOAuth2.podspec, OktaWebAuthenticationUI.podspec, README.md, Sources/AuthFoundation/OAuth2/OAuth2Client.swift, Sources/AuthFoundation/Version.swift, Sources/OktaDirectAuth/Version.swift, Sources/OktaOAuth2/Version.swift, Sources/WebAuthenticationUI/Version.swift, Tests/AuthFoundationTests/OAuth2ClientTests.swift
Certain versions of macOS provides a `URLSession.shared` instance that uses a persistent URL cache, whereas newer versions do not.  Since the `/oauth2/v1/keys` endpoint has a long cache expiry (~= 10 days), when keys are rotated on the server, users may not be unable to sign in unless they clear the cache (or delete and reinstall the app).
Since other parts of the SDK explicitly uses an ephemeral session already, this looks an oversight, so it’s good to make our uses of URLSession consistent across the SDK.
=> Ensure the default URLSession for OAuth2Client is ephemeral

Sources/AuthFoundation/Migration/Migrators/OIDCLegacyMigrator.swift, Sources/WebAuthenticationUI/WebAuthentication.swift, Tests/AuthFoundationTests/OIDCLegacyMigratorTests.swift
Client IDs for 1st party apps (like Okta Personal's iOS app) have don't match the regex. Since we have access to the client ID, we can first do a check against that instead of the regex, then default the the current behavior if that doesn't work.
This PR:
- covers the failing scenario with a unit test
- fixes the failing scenario
- also fixes a small documentation issue (removes a parameter from the docs that isn't in the actual function)
=> fix client id matching

Sources/AuthFoundation/OAuth2/OAuth2Client.swift, Sources/AuthFoundation/Utilities/UnsafeLock.swift, Tests/AuthFoundationTests/APIRetryTests.swift, Tests/AuthFoundationTests/CredentialRefreshTests.swift, Tests/AuthFoundationTests/OAuth2ClientTests.swift, Tests/TestCommon/TimeInterval+Extensions.swift, Tests/TestCommon/URLSessionMock.swift, Tests/TestCommon/XCTestCase+Extensions.swift
Current unit tests thoroughly tests concurrent accesses to refreshIfNeeded when using completion blocks, but neglects to test the Swift Concurrency equivalents to the same degree. Fortunately issue #170 has highlighted problems where this behavior doesn't work properly when using `async / await`, which results in a crash.
=> Fix concurrent accesses to the async refreshIfNeeded function

Sources/AuthFoundation/User Management/Credential.swift, Tests/AuthFoundationTests/CredentialRevokeTests.swift
Ensures completion blocks are called appropriately when removing tokens from storage fails after a successful revoke
In these cases, the completion block could be called multiple times, which breaks the swift concurrency lifecycle.
This fixes #169
=> Fix crash when using `try await credential.revoke()` if removal from token storage fails

OktaAuthFoundation.podspec, OktaDirectAuth.podspec, OktaOAuth2.podspec, OktaWebAuthenticationUI.podspec, README.md, Sources/AuthFoundation/JWT/JWTError.swift, Sources/AuthFoundation/Network/APIClientError.swift, Sources/AuthFoundation/OAuth2/OAuth2Error.swift, Sources/AuthFoundation/Resources/en.lproj/AuthFoundation.strings, Sources/AuthFoundation/Security/KeychainError.swift, Sources/AuthFoundation/Token Management/TokenError.swift, Sources/AuthFoundation/Version.swift, Sources/OktaDirectAuth/Version.swift, Sources/OktaOAuth2/Version.swift, Sources/WebAuthenticationUI/Version.swift
This also includes some API doc updates.
=> Release 1.6.0

.github/workflows/documentation-ghpages.yaml, .github/workflows/documentation.yaml, .github/workflows/lint.yaml, .github/workflows/tests.yaml, Samples/DirectAuthSignIn/DirectAuthSignIn.xcodeproj/project.pbxproj, Samples/DirectAuthSignIn/DirectAuthSignIn/ContinuationView.swift, Samples/DirectAuthSignIn/DirectAuthSignIn/PrimaryView.swift, Samples/DirectAuthSignIn/DirectAuthSignIn/SignInView.swift, Sources/OktaDirectAuth/DirectAuthFlow.swift, Sources/OktaDirectAuth/Extensions/ErrorExtensions.swift, Sources/OktaDirectAuth/Internal/Authentication Factors/ContinuationFactor.swift, Sources/OktaDirectAuth/Internal/Authentication Factors/PrimaryFactor.swift, Sources/OktaDirectAuth/Internal/Authentication Factors/SecondaryFactor.swift, Sources/OktaDirectAuth/Internal/Requests/OOBAuthenticateRequest.swift, Sources/OktaDirectAuth/Internal/Step Handlers/OOBStepHandler.swift, Sources/OktaDirectAuth/Internal/Utilities/Status+InternalExtensions.swift, Sources/OktaDirectAuth/Resources/en.lproj/OktaDirectAuth.strings, Sources/OktaDirectAuth/WebAuthn/WebAuthn.swift, Tests/OktaDirectAuthTests/DirectAuth1FATests.swift, Tests/OktaDirectAuthTests/DirectAuth2FATests.swift, Tests/OktaDirectAuthTests/ExtensionTests.swift, Tests/OktaDirectAuthTests/FactorPropertyTests.swift, Tests/OktaDirectAuthTests/FactorStepHandlerTests.swift, Tests/OktaDirectAuthTests/RequestTests.swift
This also improves how some authenticators that require user or client intervention behave. For example, WebAuthn or OV Number Challenge now return a continuation status, which can allow the application to resume consistently.
=> Add support for Phone SMS and Voice as authentication factors.

Sources/AuthFoundation/Token Management/Internal/KeychainTokenStorage.swift, Sources/AuthFoundation/Token Management/Token.swift, Sources/AuthFoundation/User Management/CredentialSecurity.swift, Tests/AuthFoundationTests/KeychainTokenStorageTests.swift
This addresses #198 by:
1. Ensuring the token metadata is stored with the appropriate accessibility settings, respecting the parent item's iCloud sync setting.
2. Returning token IDs only if both their item and metadata keychain entries can be found.
3. Establishing the `Credential.Security.isDefaultSynchronizable` property, allowing the default identifier to be shared.
This also adds unit test coverage to validate these changes.
=> Ensure token item and metadata keychain accessibility settings are consistent.

.github/workflows/documentation-ghpages.yaml, Sources/AuthFoundation/Network/APIRequest.swift, Sources/AuthFoundation/Network/APIRequestArgument.swift, Sources/AuthFoundation/Network/Internal/String+AuthFoundation.swift, Sources/AuthFoundation/OAuth2/ClientAuthentication.swift, Sources/AuthFoundation/OAuth2/OAuth2TokenRequest.swift, Sources/AuthFoundation/Requests/Token+Requests.swift, Sources/AuthFoundation/Responses/GrantType.swift, Sources/OktaDirectAuth/DirectAuthFlow.swift, Sources/OktaDirectAuth/Internal/Authentication Factors/AuthenticationFactor.swift, Sources/OktaDirectAuth/Internal/Authentication Factors/ContinuationFactor.swift, Sources/OktaDirectAuth/Internal/Authentication Factors/PrimaryFactor.swift, Sources/OktaDirectAuth/Internal/Authentication Factors/SecondaryFactor.swift, Sources/OktaDirectAuth/Internal/Requests/ChallengeRequest.swift, Sources/OktaDirectAuth/Internal/Requests/OOBAuthenticateRequest.swift, Sources/OktaDirectAuth/Internal/Requests/TokenRequest.swift, Sources/OktaDirectAuth/Internal/Requests/WebAuthnRequest.swift, Sources/OktaOAuth2/Authentication/ResourceOwnerFlow.swift, Sources/OktaOAuth2/Internal/Requests/AuthorizationCodeFlow+Requests.swift, Sources/OktaOAuth2/Internal/Requests/DeviceAuthorizeFlow+Requests.swift, Sources/OktaOAuth2/Internal/Requests/ResourceOwnerFlow+Requests.swift, Sources/OktaOAuth2/Requests/TokenExchangeFlow+Requests.swift, Tests/AuthFoundationTests/OAuth2ClientTests.swift, Tests/AuthFoundationTests/TokenTests.swift, Tests/OktaDirectAuthTests/DirectAuthenticationFlowTests.swift, Tests/OktaDirectAuthTests/FactorPropertyTests.swift, Tests/OktaDirectAuthTests/FactorStepHandlerTests.swift, Tests/OktaDirectAuthTests/RequestTests.swift, Tests/OktaOAuth2Tests/AuthorizationCodeFlowSuccessTests.swift
The APIClient system forms the foundation for most everything within the Client SDK, and as such the types and handling of data sent using these classes and protocols is of the utmost importance. To that end, this PR introduces several enhancements that will improve APIClient for future changes.
* Ensure APIRequestBody parameters use the concrete `APIRequestArgument` instead of `Any` to improve how arguments are handled, tested, and validated.
* Add `APIRequestArgument` conformances to several key types, including `JWT`, `GrantType`, and `Token.Kind`.
* Improve default `APIRequestArgument` value conversion for types that already conform to `RawRepresentable` with a `String` value type.
* Ensure `SDKVersion.register` is thread-safe, and begin initial adoption of the `Sendable` protocol.
=> API request usability and stability improvements

Sources/AuthFoundation/Security/Internal/Keychain+Extensions.swift, Sources/AuthFoundation/Security/Keychain.swift, Tests/AuthFoundationTests/KeychainTests.swift
Under some circumstances, requests to delete a Keychain item could result in calls that used invalid request attributes / filters, or includes too many arguments that prevents old values from being deleted.
=> Ensure Keychain SecItemDelete is not called with unsupported attributes

Sources/BrowserSignin/BrowserSignin.swift, Sources/BrowserSignin/Internal/BrowserSigninError+Extensions.swift, Sources/BrowserSignin/Providers/AuthenticationServicesProvider.swift, Sources/BrowserSignin/Providers/BrowserSigninProvider.swift, Sources/BrowserSignin/Resources/en.lproj/BrowserSignin.strings, Tests/BrowserSigninTests/AuthenticationServicesProviderTests.swift, Tests/BrowserSigninTests/BrowserSigninFlowTests.swift, Tests/BrowserSigninTests/BrowserSigninMocks.swift
Availability checks produced some errors under Xcode 26 on tvOS, and add missing descriptions for some new errors.
=> Fix problems with BrowserSignin on tvOS
